"""add index to created at field

Revision ID: 176823ba0308
Revises: f532d80e2748
Create Date: 2026-07-31 10:40:50.346486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176823ba0308'
down_revision: Union[str, Sequence[str], None] = 'f532d80e2748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_amenities_created_at_desc', 'amenities', [sa.literal_column('created_at DESC')], unique=False)
    op.create_foreign_key(None, 'bed_types', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_booking_rooms_created_at_desc', 'booking_rooms', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_folio_charges_created_at_desc', 'folio_charges', [sa.literal_column('created_at DESC')], unique=False)
    op.create_foreign_key(None, 'folios', 'bookings', ['booking_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'room_types', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('rooms_bed_type_id_fkey'), 'rooms', type_='foreignkey')
    op.drop_constraint(op.f('rooms_room_type_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'room_types', ['room_type_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'rooms', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rooms', 'bed_types', ['bed_type_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_room_type_id_fkey'), 'rooms', 'room_types', ['room_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('rooms_bed_type_id_fkey'), 'rooms', 'bed_types', ['bed_type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'room_types', type_='foreignkey')
    op.drop_constraint(None, 'folios', type_='foreignkey')
    op.drop_index('idx_folio_charges_created_at_desc', table_name='folio_charges')
    op.drop_index('idx_booking_rooms_created_at_desc', table_name='booking_rooms')
    op.drop_constraint(None, 'bed_types', type_='foreignkey')
    op.drop_index('idx_amenities_created_at_desc', table_name='amenities')
    
    # ### end Alembic commands ###
