"""initial schema

Revision ID: 8252633d3707
Revises:
Create Date: 2026-06-23 10:42:24.938328

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8252633d3707"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column(
            "plan",
            sa.Enum("FREE", "PREMIUM", "ENTERPRISE", name="plan"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", name="status"),
            nullable=False,
        ),
        sa.Column("custom_domain", sa.String(length=255), nullable=True),
        sa.Column("logo_url", sa.String(length=2048), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        # sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("custom_domain"),
        sa.UniqueConstraint("owner_id", "name", name="uq_tenant_owner_name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_tenants_owner_id"), "tenants", ["owner_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "guest_loyalty",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guest_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("loyalty_tier", sa.String(length=50), nullable=False),
        sa.Column("total_points", sa.Integer(), nullable=False),
        sa.CheckConstraint("total_points >= 0", name="chk_positive_points"),
        sa.ForeignKeyConstraint(["guest_id"], ["guests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guest_id", "tenant_id", name="uq_guest_tenant_loyalty"),
    )
    op.create_index(
        op.f("ix_guest_loyalty_guest_id"), "guest_loyalty", ["guest_id"], unique=False
    )
    op.create_index(
        op.f("ix_guest_loyalty_tenant_id"), "guest_loyalty", ["tenant_id"], unique=False
    )
    op.create_table(
        "properties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("country", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("zip_code", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("check_in_time_from", sa.Time(), nullable=False),
        sa.Column("check_in_time_to", sa.Time(), nullable=False),
        sa.Column("check_out_time_from", sa.Time(), nullable=False),
        sa.Column("check_out_time_to", sa.Time(), nullable=False),
        sa.Column("number_of_floors", sa.Integer(), nullable=False),
        sa.Column("total_rooms", sa.Integer(), nullable=False),
        sa.Column("year_built", sa.Integer(), nullable=True),
        sa.Column("amenities", sa.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_properties_tenant_id"), "properties", ["tenant_id"], unique=False
    )
    op.create_table(
        "property_photos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("photo_url", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_property_photos_property_id"),
        "property_photos",
        ["property_id"],
        unique=False,
    )
    op.create_foreign_key(
        constraint_name="fk_tenants_owner_id_users",
        source_table="tenants",
        referent_table="users",
        local_cols=["owner_id"],
        remote_cols=["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tenants_owner_id_users', 'tenants', type_='foreignkey')
    op.drop_index(op.f("ix_property_photos_property_id"), table_name="property_photos")
    op.drop_table("property_photos")
    op.drop_index(op.f("ix_properties_tenant_id"), table_name="properties")
    op.drop_table("properties")
    op.drop_index(op.f("ix_guest_loyalty_tenant_id"), table_name="guest_loyalty")
    op.drop_index(op.f("ix_guest_loyalty_guest_id"), table_name="guest_loyalty")
    op.drop_table("guest_loyalty")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tenants_owner_id"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_table("guests")
    # ### end Alembic commands ###
