"""add guest_favorites table

Revision ID: a1fe580dbc7d
Revises: cccab3fed9fd
Create Date: 2026-08-23 16:16:14.226571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1fe580dbc7d'
down_revision: Union[str, Sequence[str], None] = 'cccab3fed9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop dependent child tables and their indexes FIRST (safely ignoring if already gone)
    op.drop_index(op.f('ix_housekeeping_tasks_status'), table_name='housekeeping_tasks', if_exists=True)
    op.drop_index(op.f('ix_housekeeping_tasks_room_id'), table_name='housekeeping_tasks', if_exists=True)
    op.drop_index(op.f('ix_housekeeping_tasks_property_id'), table_name='housekeeping_tasks', if_exists=True)
    op.drop_index(op.f('ix_housekeeping_tasks_due_time'), table_name='housekeeping_tasks', if_exists=True)
    op.drop_index(op.f('ix_housekeeping_tasks_assigned_staff_id'), table_name='housekeeping_tasks', if_exists=True)
    
    # Use standard execute with IF EXISTS for dropping the tables if they were partially dropped
    op.execute("DROP TABLE IF EXISTS housekeeping_tasks CASCADE;")
    op.execute("DROP TABLE IF EXISTS staff_properties CASCADE;")
    op.execute("DROP TABLE IF EXISTS staffs CASCADE;")

    # 3. Drop property trgm indexes safely
    op.drop_index(op.f('ix_properties_address_trgm'), table_name='properties', postgresql_ops={'address': 'gin_trgm_ops'}, postgresql_using='gin', if_exists=True)
    op.drop_index(op.f('ix_properties_city_trgm'), table_name='properties', postgresql_ops={'city': 'gin_trgm_ops'}, postgresql_using='gin', if_exists=True)
    op.drop_index(op.f('ix_properties_country_trgm'), table_name='properties', postgresql_ops={'country': 'gin_trgm_ops'}, postgresql_using='gin', if_exists=True)
    op.drop_index(op.f('ix_properties_name_trgm'), table_name='properties', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin', if_exists=True)
    op.drop_index(op.f('ix_properties_state_trgm'), table_name='properties', postgresql_ops={'state': 'gin_trgm_ops'}, postgresql_using='gin', if_exists=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    
    # Recreate parent table first
    op.create_table('staffs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('job_role', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('monthly_salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"profile": null, "citizenship_back": null, "citizenship_front": null}\'::jsonb'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('monthly_salary >= 0::numeric', name=op.f('chk_staff_salary_non_negative')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('staffs_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('staffs_pkey'))
    )
    op.create_index(op.f('ix_staffs_email'), 'staffs', ['email'], unique=True)
    op.create_index(op.f('ix_staffs_status'), 'staffs', ['status'], unique=False)
    op.create_index(op.f('ix_staffs_tenant_id'), 'staffs', ['tenant_id'], unique=False)

    # Recreate child tables
    op.create_table('staff_properties',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('staff_properties_property_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], name=op.f('staff_properties_staff_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('staff_properties_pkey')),
    sa.UniqueConstraint('staff_id', 'property_id', name=op.f('uq_staff_property'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_staff_properties_property_id'), 'staff_properties', ['property_id'], unique=False)
    op.create_index(op.f('ix_staff_properties_staff_id'), 'staff_properties', ['staff_id'], unique=False)

    op.create_table('housekeeping_tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('assigned_staff_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('due_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('due_time IS NOT NULL', name=op.f('chk_task_due_time_required')),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('housekeeping_tasks_assigned_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['staffs.id'], name=op.f('housekeeping_tasks_assigned_staff_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('housekeeping_tasks_property_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('housekeeping_tasks_room_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('housekeeping_tasks_pkey'))
    )
    op.create_index(op.f('ix_housekeeping_tasks_assigned_staff_id'), 'housekeeping_tasks', ['assigned_staff_id'], unique=False)
    op.create_index(op.f('ix_housekeeping_tasks_due_time'), 'housekeeping_tasks', ['due_time'], unique=False)
    op.create_index(op.f('ix_housekeeping_tasks_property_id'), 'housekeeping_tasks', ['property_id'], unique=False)
    op.create_index(op.f('ix_housekeeping_tasks_room_id'), 'housekeeping_tasks', ['room_id'], unique=False)
    op.create_index(op.f('ix_housekeeping_tasks_status'), 'housekeeping_tasks', ['status'], unique=False)
    # ### end Alembic commands ###