"""number of adults and children column added in the booking

Revision ID: ab39a17c3f72
Revises: 176823ba0308
Create Date: 2026-07-31 16:54:30.362315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab39a17c3f72'
down_revision: Union[str, Sequence[str], None] = '176823ba0308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_properties_property_id'), table_name='staff_properties')
    op.drop_index(op.f('ix_staff_properties_staff_id'), table_name='staff_properties')
    op.drop_table('staff_properties')
    op.drop_index(op.f('ix_staffs_email'), table_name='staffs')
    op.drop_index(op.f('ix_staffs_status'), table_name='staffs')
    op.drop_index(op.f('ix_staffs_tenant_id'), table_name='staffs')
    op.drop_table('staffs')
    op.add_column('bookings', sa.Column('number_of_adults', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('bookings', sa.Column('number_of_children', sa.Integer(), nullable=False, server_default='0'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'number_of_children')
    op.drop_column('bookings', 'number_of_adults')
    op.create_table('staffs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('job_role', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('monthly_salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"profile": null, "citizenship_back": null, "citizenship_front": null}\'::jsonb'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('monthly_salary >= 0::numeric', name=op.f('chk_staff_salary_non_negative')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('staffs_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('staffs_pkey'))
    )
    op.create_index(op.f('ix_staffs_tenant_id'), 'staffs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_staffs_status'), 'staffs', ['status'], unique=False)
    op.create_index(op.f('ix_staffs_email'), 'staffs', ['email'], unique=True)
    op.create_table('staff_properties',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('staff_properties_property_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], name=op.f('staff_properties_staff_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('staff_properties_pkey')),
    sa.UniqueConstraint('staff_id', 'property_id', name=op.f('uq_staff_property'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_staff_properties_staff_id'), 'staff_properties', ['staff_id'], unique=False)
    op.create_index(op.f('ix_staff_properties_property_id'), 'staff_properties', ['property_id'], unique=False)
    # ### end Alembic commands ###
