"""adding password reset token

Revision ID: d4be4e5e74e3
Revises: ab39a17c3f72
Create Date: 2026-08-04 10:30:59.312533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4be4e5e74e3'
down_revision: Union[str, Sequence[str], None] = 'ab39a17c3f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(user_id IS NOT NULL AND guest_id IS NULL) OR (user_id IS NULL AND guest_id IS NOT NULL)', name='chk_reset_token_exactly_one_owner'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_guest_id'), 'password_reset_tokens', ['guest_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_index(op.f('ix_staff_properties_property_id'), table_name='staff_properties')
    op.drop_index(op.f('ix_staff_properties_staff_id'), table_name='staff_properties')
    op.drop_table('staff_properties')
    op.drop_index(op.f('ix_staffs_email'), table_name='staffs')
    op.drop_index(op.f('ix_staffs_status'), table_name='staffs')
    op.drop_index(op.f('ix_staffs_tenant_id'), table_name='staffs')
    op.drop_table('staffs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('job_role', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('monthly_salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"profile": null, "citizenship_back": null, "citizenship_front": null}\'::jsonb'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('monthly_salary >= 0::numeric', name=op.f('chk_staff_salary_non_negative')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('staffs_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('staffs_pkey'))
    )
    op.create_index(op.f('ix_staffs_tenant_id'), 'staffs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_staffs_status'), 'staffs', ['status'], unique=False)
    op.create_index(op.f('ix_staffs_email'), 'staffs', ['email'], unique=True)
    op.create_table('staff_properties',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('staff_properties_property_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], name=op.f('staff_properties_staff_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('staff_properties_pkey')),
    sa.UniqueConstraint('staff_id', 'property_id', name=op.f('uq_staff_property'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_staff_properties_staff_id'), 'staff_properties', ['staff_id'], unique=False)
    op.create_index(op.f('ix_staff_properties_property_id'), 'staff_properties', ['property_id'], unique=False)
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_guest_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
